Vagrant.configure(2) do |config|
config.vm.box = "generic/centos8s"
config.vm.provider "virtualbox" do |v|
v.memory = 1024
v.cpus = 2
end

config.vm.define "nginx" do |nginx|
nginx.vm.hostname = "nginx"
nginx.vm.provision "shell", path: "script.sh"
end
end
