Vagrant.configure(2) do |config|
config.vm.box = "generic/centos8s"
config.vm.provider "virtualbox" do |v|
v.memory = 512
v.cpus = 1
end

config.vm.define "nginx" do |nginx|
nginx.vm.network "private_network", ip: "192.168.50.10",
virtualbox__intnet: "net1"
nginx.vm.hostname = "nginx"
nginx.vm.provision "shell", path: "script.sh"
end
end
