Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
     vb.cpus = "2"
  end
   config.vm.network "private_network", ip: "192.168.56.10"
   config.vm.provision "shell", inline: <<-SHELL
#     yum update -y
     yum install -y nano
     yum install -y net-tools
     yum install wget vim -y
   SHELL

   config.vm.provision "shell", path: "script01.sh", privileged: true

  config.vm.synced_folder "files", "/vagrant"
  config.vm.provision "shell",
    inline: "cp /vagrant/prometheus.yml /etc/prometheus/prometheus.yml && cp /vagrant/prometheus.service /etc/systemd/system/prometheus.service && cp /vagrant/node_exporter.service /etc/systemd/system/node_exporter.service && cp /vagrant/grafana_enterprise_9.5.2_1.x86_64-364648-d7217e.rpm /root/grafana_enterprise_9.5.2_1.x86_64-364648-d7217e.rpm"

   config.vm.provision "shell", path: "script02.sh", privileged: true
end
